qwen1.5-1.8b: /mnt/hwfile/medai/LLMModels/Model/Qwen1.5-1.8B-Chat
qwen1.5-7b: /mnt/hwfile/medai/LLMModels/Model/Qwen1.5-7B-Chat
qwen1.5-14b: /mnt/hwfile/medai/LLMModels/Model/Qwen1.5-14B-Chat
qwen1.5-32b: /mnt/hwfile/medai/LLMModels/Model/Qwen1.5-32B-Chat
qwen2-7b: /mnt/hwfile/medai/LLMModels/Model/Qwen2-7B-Instruct-lys
qwen2-72b: /mnt/hwfile/medai/LLMModels/Model/Qwen2-72B-Instruct-GPTQ-Int4
qwen2.5-0.5b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-0.5B-Instruct
qwen2.5-1.5b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-1.5B-Instruct
qwen2.5-3b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-3B-Instruct/
qwen2.5-7b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-7B-Instruct
qwen2.5-32b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-32B-Instruct-GPTQ-Int4/
qwen2.5-72b: /mnt/hwfile/medai/LLMModels/Model/Qwen2.5-72B-Instruct-AWQ/
llama3-8b-base: /mnt/hwfile/medai/LLMModels/Model/Meta-Llama-3-8B 
llama3-8b: /mnt/hwfile/medai/LLMModels/Model/Meta-Llama-3-8B-Instruct
llama3-70b: /mnt/hwfile/medai/LLMModels/Model/Meta-Llama-3-70B-Instruct-GPTQ
llama3.2-1b: /mnt/hwfile/medai/LLMModels/Model/Llama-3.2-1B-Instruct
llama3.2-3b: /mnt/hwfile/medai/LLMModels/Model/Llama-3.2-3B-Instruct
llama3.1-8b: /mnt/hwfile/medai/LLMModels/Model/Meta-Llama-3.1-8B-Instruct
llama3.1-70b: /mnt/hwfile/medai/LLMModels/Model/Meta-Llama-3.1-70B-Instruct-AWQ-INT4
medllama3-8b: /mnt/hwfile/medai/LLMModels/Model/MedLlama-3-8b-v2.0
mmed-llama3: /mnt/hwfile/medai/LLMModels/Model/MMed-Llama-3-8B
mmeds-llama3: /mnt/hwfile/medai/LLMModels/Model/MMedS-Llama3-3-8B
openbiollm: /mnt/hwfile/medai/LLMModels/Model/Llama3-OpenBioLLM-8B/
qwq-preview: /mnt/hwfile/medai/LLMModels/Model/QwQ-32B-Preview/
qwq: /mnt/hwfile/medai/LLMModels/Model/QwQ-32B
llama3-med42: /mnt/hwfile/medai/LLMModels/Model/Llama3-Med42-8B
huatuo-o1: /mnt/hwfile/medai/LLMModels/Model/HuatuoGPT-o1-8B
ultramedical-8b: /mnt/hwfile/medai/LLMModels/Model/Llama-3-8B-UltraMedical
ultramedical3.1-8b: /mnt/hwfile/medai/LLMModels/Model/Llama-3.1-8B-UltraMedical
phi3.5: /mnt/hwfile/medai/LLMModels/Model/Phi-3.5-mini-instruct
medverifier-3b: /mnt/hwfile/medai/LLMModels/Model/medical_o1_verifier_3B
medmobile: /mnt/hwfile/medai/LLMModels/Model/MedMobile
phi4-mini: /mnt/hwfile/medai/LLMModels/Model/Phi-4-mini-instruct







  


